stages:
  - set_variables
  - build
  - deploy

cache:
  paths:
    - .env

set_variables:
  stage: set_variables
  environment: "staging"
  cache:
    policy: push
    paths:
      - .env
  script:
    - chmod +x set-gitlab-variables.sh
    - ./set-gitlab-variables.sh
  only:
    - "${BRANCH_NAME}"
  tags:
    - arge-server

build:
  stage: build
  needs: [ set_variables ]
  cache:
    policy: pull
    paths:
      - .env
  variables:
    PROJECT_FOLDER: "${PROJECT_PATH}/${CI_PROJECT_NAME}_${CI_PROJECT_ID}"
  script:
    - mkdir -p ${PROJECT_FOLDER} && rm -rf ${PROJECT_FOLDER}/.* 2>/dev/null
    - rsync -av --progress . ${PROJECT_FOLDER} --exclude .git
    - cd ${PROJECT_FOLDER} && docker-compose up -d --build --remove-orphans
  only:
    - "${BRANCH_NAME}"
  tags:
    - arge-server
