stages:
  - set_variables
  - build
  - deploy

cache:
  paths:
    - .env

set_variables:
  stage: set_variables
  environment: "staging"
  cache:
    policy: push
    paths:
      - .env
  script:
    - chmod +x set-gitlab-variables.sh
    - ./set-gitlab-variables.sh
  only:
    - master
  tags:
    - arge-server

build:
  stage: build
  needs: [ set_variables ]
  cache:
    policy: pull
    paths:
      - .env
  variables:
    PROJECT_PATH: "/arge/${CI_PROJECT_NAME}_${CI_PROJECT_ID}"
  script:
    - mkdir -p ${PROJECT_PATH} && rm -rf ${PROJECT_PATH}/.* 2>/dev/null
    - rsync -av --progress . ${PROJECT_PATH} --exclude .git
    - cd ${PROJECT_PATH} && docker-compose up -d --build --remove-orphans
  only:
    - master
  tags:
    - arge-server
