stages:
  - set_variables
  - build
  - deploy

cache:
  paths:
    - .env

set_variables:
  stage: set_variables
  environment: "staging"
  cache:
    policy: push
    paths:
      - .env
  script:
    - chmod +x set-gitlab-variables.sh
    - ./set-gitlab-variables.sh
  only:
    - main
  tags:
    - arge-server

build:
  stage: build
  needs: [set_variables]
  cache:
    policy: pull
    paths:
      - .env
  variables:
    PROJECT_FOLDER: "${CI_PROJECT_NAME}_${CI_PROJECT_ID}"
  script:
    - rm -rf /arge/${PROJECT_FOLDER}/.* 2> /dev/null && mkdir -p /arge/${PROJECT_FOLDER}
    - rsync -av --progress . /arge/${PROJECT_FOLDER} --exclude .git
    - cd /arge/${PROJECT_FOLDER} && chmod +x *.sh && ./run-docker.sh
  only:
    - main
  tags:
    - arge-server
